# Generated by Django 2.2.4 on 2022-10-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='shop_permit',
            field=models.IntegerField(blank=True, default=123),
            preserve_default=False,
        ),
    ]
