# Generated by Django 2.2.4 on 2022-10-10 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0002_customer_shop_permit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='customers',
        ),
        migrations.RemoveField(
            model_name='car',
            name='engine',
        ),
        migrations.AlterField(
            model_name='car',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='rental_app.Provider'),
        ),
    ]
