# Generated by Django 2.2.4 on 2022-10-11 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0003_auto_20221011_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='shop_permit',
        ),
    ]
